#!/bin/bash
#============================================================================
# ${XEN_SCRIPT_DIR}/vif-link-route-default-gateway
#
# Script for configuring a vif in link routed mode and then setting that
# link gateway address as the default gateway address.
#
# Usage:
# vif-link-route-default-gateway (add|remove|online|offline)
#
# Environment vars:
# dev         vif interface name (required).
# XENBUS_PATH path to this device's details in the XenStore (required).
#
# Read from the store:
# ip      list of IP networks for the vif, space-separated (default given in
#         this script).
#============================================================================

dir=$(dirname "$0")
. "${dir}/vif-common.sh"

ip_addr=${ip%:*}
ip_mask=${ip#*:}

case "${command}" in
	online)
		ifconfig ${dev} ${ip_addr} netmask ${ip_mask} up
		echo 1 >/proc/sys/net/ipv4/conf/${dev}/proxy_arp
		ipcmd='add'
		cmdprefix=''
		;;
	offline)
		do_without_error ifdown ${dev}
		ipcmd='del'
		cmdprefix='do_without_error'
		;;
esac

${cmdprefix} ip route ${ipcmd} default via ${ip_addr}

call_hooks vif post

log debug "Successful vif-link-route-default-gateway ${command} for ${dev} using ${ip_addr} : ${ip_mask}."
if [ "${command}" = "online" ]
then
	success
fi
