#!/bin/bash
#============================================================================
# ${XEN_SCRIPT_DIR}/vif-link-route
#
# Script for configuring a vif in link routed mode.
#
# Usage:
# vif-link-route (add|remove|online|offline)
#
# Environment vars:
# dev         vif interface name (required).
# XENBUS_PATH path to this device's details in the XenStore (required).
#
# Read from the store:
# ip      list of IP networks for the vif, space-separated (default given in
#         this script).
#============================================================================

dir=$(dirname "$0")
# shellcheck disable=SC1090
. "${dir}/vif-common.sh"

# shellcheck disable=SC2154
ip_addr=${ip%:*}
ip_mask=${ip#*:}

# shellcheck disable=SC2154
case "${command}" in
	online)
		ifconfig "${dev}" "${ip_addr}" netmask "${ip_mask}" up
		echo 1 >/proc/sys/net/ipv4/conf/"${dev}"/proxy_arp
		;;
	offline)
		do_without_error ifdown "${dev}"
		;;
esac

call_hooks vif post

log debug "Successful vif-link-route ${command} for ${dev} using ${ip_addr} : ${ip_mask}."
if [ "${command}" = "online" ]
then
	success
fi
